export enum DocumentDeliveryStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  SENDING = 'SENDING',
  DELIVERED = 'DELIVERED',
  RETRY_PENDING = 'RETRY_PENDING',
  FAILED = 'FAILED',
  MANUAL_REVIEW_REQUIRED = 'MANUAL_REVIEW_REQUIRED',
  CANCELLED = 'CANCELLED',
}
